ALoop registration
CardanoMDP/CardanoMDP-adapools-org-alliance pull request #104
Opened 2021-07-21 03:50 UTC by aloopmarin007

2021-07-21 09:58 UTC, ResponsibleStaking requested changes

2021-07-21 09:58 UTC, ResponsibleStaking commented on cardano-mdp.json
> +               "member_since": "2021-06-06",
You have submitted a PR previously which is merged in the meanwhile.
The new PR contains a different date. Is there a reason for this? I beliefe the other date was OK. So I would close this PR if you don't mind.

2021-07-27 19:06 UTC, ResponsibleStaking commented
Closing because of inactivity and no further relevant action.

2021-07-27 19:06 UTC, closed without merging

2021-07-27 20:31 UTC, aloopmarin007 commented
I did a second PR to reflect the changes on pool registration. But It's all good, now